name: Check code

on:
  push:
  pull_request:

jobs:

  check:
    name: Run checks - PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1]
        dependency-version: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: '**/vendor'
          key: ${{ runner.os }}-vendor-cache-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-vendor-cache-

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Validate Composer configuration file
        run: composer validate --strict

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Lint code
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run tests
        run: vendor/bin/phpunit
